version: '3.8'

services:
  bank-app:
    build: .
    image: bank-2025:v1
    container_name: trnsaction-app  # container name is optional
    ports:
      - '3000:3000'

    environment:
      - MONGODB_URI=mongodb://mongodb:27017/transactionhistory

    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
